[package]
name = "playit-api-client"
version = "0.1.0"
edition = "2021"
description = "Contains the logic to create a playit.gg agent"
license = "BSD-2-Clause"
repository = "https://github.com/playit-cloud/playit-agent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
byteorder = { workspace = true }
reqwest = { version = "0.12", features = ["json", "native-tls-vendored"] }

[dev-dependencies]
tracing-subscriber = { workspace = true }

# hyper = { version = "1.4", features = ["client", "http2", "http1"] }
# bytes = "1.7"
# time = "0.3.36"
# hyper-util = { version = "0.1.7", features = ["client", "client-legacy", "http1", "http2"] }
# http-body-util = "0.1.2"
# hyper-rustls = { version = "0.27", features = ["http2", "webpki-roots"] }

# rustls = { version = "0.23", default-features = false, features = ["ring"] }
