[workspace]
members = [
    "packages/agent_cli",
    "packages/agent_core",
    "packages/agent_proto",
]

[workspace.dependencies]
tokio = { version = "1.32", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8.5"
hex = "0.4.3"
toml = "0.7.6"
uuid = { version = "1.4", features = ["serde"] }
byteorder = "1.4.3"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }

[profile.release]
strip = "debuginfo"
opt-level = "z"
lto = true
codegen-units = 1
