[package]
name = "playit-agent-core"
version = "0.10.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
hex =  { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }
byteorder = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }

hyper = { version = "0.14", features = ["client", "http2", "http1"] }
hyper-rustls = { version = "0.24", features = ["http2"] }

playit-agent-proto = { path = "../agent_proto" }

[[example]]
name = "echo_tunnel"
path = "./examples/echo_tunnel.rs"
