[package]
name = "playit-agent-core"
version.workspace = true
edition = "2021"
description = "Contains the logic to create a playit.gg agent"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
hex =  { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }
byteorder = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
futures-util = { workspace = true }

hyper = { version = "1.2", features = ["client", "http2", "http1"] }
bytes = "1.5.0"
time = "0.3.36"
hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "http1", "http2"] }
http-body-util = "0.1.0"
hyper-rustls = { version = "0.26", features = ["http2", "webpki-roots"] }

playit-agent-proto = { path = "../agent_proto", version = "0.15.13" }
