[package]
name = "playit-agent-core"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
tokio = { version = "1.20", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8.5"
hyper = { version = "0.14.20", features = ["client", "http2", "http1"] }
hyper-rustls = { version = "0.23.0", features = ["http2"] }
hex = "0.4.3"
toml = "0.5.9"
byteorder = "1.4.3"
playit-agent-proto = { path = "../agent_proto" }
uuid = { version = "1.1.2", features = ["serde"] }
async-trait = "0.1.60"
chrono = { version = "0.4", features = ["serde"] }

[[example]]
name = "echo_tunnel"
path = "./examples/echo_tunnel.rs"
