[package]
name = "playit-cli"
version.workspace = true
edition = "2021"
authors = ["Patrick Lorio <patrick@playit.gg>"]
description = "Making it easy to play games with friends. Makes your server public"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

clap = { version = "4.4", features = ["derive"] }
urlencoding = "2.1"
serde_yaml = "0.9"
crossterm = "0.26"
dirs = "5.0.1"
tracing-appender = "0.2"

playit-agent-core = { path = "../agent_core" }
playit-agent-proto = { path = "../agent_proto" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
