[package]
name = "playit-ping-monitor"
version = "0.1.0"
edition = "2021"
description = "Runs ping experiments to the playit network to help us tune routing"
license = "BSD-2-Clause"
repository = "https://github.com/playit-cloud/playit-agent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

message-encoding = { workspace = true }
rand = { workspace = true }

serde = { workspace = true}
toml = { workspace = true }
hex = { workspace = true }
dirs = { workspace = true }

playit-agent-proto = { path = "../agent_proto", version = "1.0.0" }
playit-api-client = { path = "../api_client", version = "0.1.0" }