[package]
name = "playit-agent-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
hex = { workspace = true }
byteorder = { workspace = true }

sha2 = "0.10"
hmac = "0.12"

[dev-dependencies]
rand = { workspace = true }