name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos intel
            os: macos-latest
            arch: x86_64-apple-darwin
            artifact: playit-darwin-intel

          - name: macos arm
            os: macos-latest
            arch: aarch64-apple-darwin
            artifact: playit-darwin-arm

          - name: linux 64bit
            os: ubuntu-latest
            arch: x86_64-unknown-linux-musl
            artifact: playit-linux-amd64

          - name: linux arm64
            os: ubuntu-latest
            arch: aarch64-unknown-linux-musl
            artifact: playit-linux-aarch64

          - name: linux arm32
            os: ubuntu-latest
            arch: arm-unknown-linux-musleabi
            artifact: playit-linux-arm

          - name: windows 32bit
            os: windows-latest
            arch: i686-pc-windows-msvc
            artifact: playit-windows-i686.exe

          - name: windows 64bit
            os: windows-latest
            arch: x86_64-pc-windows-msvc
            artifact: playit-windows-amd64.exe

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.arch }}
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all

      - name: Upload .exe
        if: matrix.platform.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/playit-cli.exe
          asset_name: ${{ matrix.platform.artifact }}
          asset_content_type: application/octet-stream

      - name: Upload Binary
        if: matrix.platform.os != 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/playit-cli
          asset_name: ${{ matrix.platform.artifact }}
          asset_content_type: application/octet-stream
